version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - apoc.export.file.enabled=true
      - apoc.import.file.enabled=true
      - dbms.security.procedures.unrestricted=apoc.*
      - dbms.security.procedures.allowlist=apoc.*
    volumes:
      - neo4j_data:/data
      - ./exports:/var/lib/neo4j/import

  backend:
    build: ./backend
    restart: unless-stopped
    depends_on:
      - neo4j
    ports:
      - "8000:8000"
    env_file: backend/.env.development 
    volumes:
      - ./backend:/app  # Mount app, but keep dependencies inside the container
      - ./pdf_files:/pdf_files
      - ./nltk_data:/root/nltk_data
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3001:3000"
    environment:
    - CHOKIDAR_USEPOLLING=true
    - WATCHPACK_POLLING=true
    - FAST_REFRESH=true
    - WDS_SOCKET_PORT=3000      
    - REACT_APP_API_URL=http://localhost:8000

    command: npm start

volumes:
  neo4j_data:
