version: '3.8'

services:
  backend:
    build: ./backend
    restart: unless-stopped
    expose:
      - "8000"
    env_file: ./backend/.env.production

  neo4j:
    image: neo4j:latest
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - neo4j_data:/data

  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: unless-stopped

volumes:
  neo4j_data:
