version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    restart: unless-stopped
    ports:
      - "7474:7474"  # Web UI
      - "7687:7687"  # Bolt protocol
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - neo4j_data:/data

  backend:
    build: ./backend
    restart: unless-stopped
    depends_on:
      - neo4j
    ports:
      - "8000:8000"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
    volumes:
      - ./backend:/app  # Mount app, but keep dependencies inside the container
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3001:3000"
    environment:
    - CHOKIDAR_USEPOLLING=true
    - WATCHPACK_POLLING=true
    - FAST_REFRESH=true
    - WDS_SOCKET_PORT=3000      
    - REACT_APP_API_URL=http://localhost:8000

    command: npm start

volumes:
  neo4j_data:
