export const layoutConfig = {
  name: 'cose-bilkent',
  animate: false,
  refresh: false,
  randomize: true,
  padding: 10,
  idealEdgeLength: 180,
  nodeRepulsion: 8000,
  edgeElasticity: 0.3,
  nestingFactor: 2,
  gravity: 10,
  gravityRangeCompound: 1.2,
  gravityCompound: 0.4,
  gravityRange: 10,
  tilingPaddingVertical: 10,
  tilingPaddingHorizontal: 1500,
  nodeDimensionsIncludeLabels: true,
  fit: true,
};
