const defaultCoseLayout = {
  name: 'cose-bilkent',
  quality: 'proof',                 
  nodeDimensionsIncludeLabels: false,
  refresh: 30,
  fit: true,
  padding: 50,                      
  randomize: false,               
  nodeRepulsion: 25000,            
  idealEdgeLength: 170,           
  edgeElasticity: 0.1,
  nestingFactor: 1,
  gravity: 0.4,                     
  numIter: 20000,                  
  tile: true,
  animate: false,                  
  animationDuration: 0,
  tilingPaddingVertical: 10,
  tilingPaddingHorizontal: 10,
  gravityRangeCompound: 1.8,
  gravityCompound: 1.2,
  gravityRange: 100,
  initialEnergyOnIncremental: 0.3,
};

const defaultCoseLayout_2 = {
  name: 'cose-bilkent',
  quality: 'default',
  nodeDimensionsIncludeLabels: false,
  refresh: 30,
  fit: true,
  padding: 30,
  randomize: true,
  nodeRepulsion: 10000,
  idealEdgeLength: 120,
  edgeElasticity: 0.1,
  nestingFactor: 20,
  gravity: 0.1,
  numIter: 12500,
  tile: true,
  animate: 'end',
  animationDuration: 500,
  tilingPaddingVertical: 10,
  tilingPaddingHorizontal: 200,
  gravityRangeCompound: 1.5,
  gravityCompound: 1.0,
  gravityRange: 10,
  initialEnergyOnIncremental: 0.5,
};

export const layoutConfig = {
  HE_2025: defaultCoseLayout,
  Cluster_2: {
    name: 'klay',
    fit: true,
    padding: 5,
    animate: false,
    klay: {
      direction: 'DOWN',
      aspectRatio: 0.5,
      borderSpacing: 1,
      spacing: 50,
      edgeSpacingFactor: 0.2,
      inLayerSpacingFactor: 0.1,
      nodeLayering: 'NETWORK_SIMPLEX',
      nodePlacement: 'LINEAR_SEGMENTS',
      crossingMinimization: 'LAYER_SWEEP',
      cycleBreaking: 'GREEDY',
      edgeRouting: 'ORTHOGONAL',
      layoutHierarchy: true,
      separateConnectedComponents: true,
      thoroughness: 20,
      randomizationSeed: 1
    }
  },
  Cluster_4: {
    name: 'klay',
    fit: true,
    padding: 5,
    animate: false,
    klay: {
      direction: 'DOWN',
      aspectRatio: 0.3,
      borderSpacing: 1,
      spacing: 40,
      edgeSpacingFactor: 0.2,
      inLayerSpacingFactor: 0.1,
      nodeLayering: 'NETWORK_SIMPLEX',
      nodePlacement: 'LINEAR_SEGMENTS',
      crossingMinimization: 'LAYER_SWEEP',
      cycleBreaking: 'GREEDY',
      edgeRouting: 'ORTHOGONAL',
      layoutHierarchy: true,
      separateConnectedComponents: true,
      thoroughness: 20,
      randomizationSeed: 1
    }
  },
  Cluster_2_cose: defaultCoseLayout_2,
  Cluster_4_cose: defaultCoseLayout_2
};
